predicted-labels:
    test1: 'test1'
    test2: 'test2'
    area/enterprise_readiness: 'area/enterprise_readiness'
    improvement/enhancement: 'improvement/enhancement'
    priority/p0: 'priority/p0'
    priority/p1: 'priority/p1'
    priority/p2: 'priority/p2'
    kind/bug: 'kind/bug'
    community/question: 'community/question'
    area/tfjob: 'area/tfjob'
    area/inference: 'area/inference'
    area/kfctl: 'area/kfctl'
    area/jupyter: 'area/jupyter'
    area/front-end: 'area/front-end'
    area/docs: 'area/docs'
    area/build-release: 'area/build-release'
    area/ksonnet: 'area/ksonnet'
    area/bootstrap: 'area/bootstrap'
    area/testing: 'area/testing'
    area/enterprise_readiness: 'area/enterprise_readiness'
    area/openmpi: 'area/openmpi'
    area/centraldashboard: 'area/centraldashboard'
    area/pipelines: 'area/pipelines'
    lifecycle/stale: 'lifecycle/stale'
    area/example/code_search: 'area/example/code_search'
    area/example/issue_summarization: 'area/example/issue_summarization'
    platform/gcp: 'platform/gcp'
